# Generated by Django 4.0.6 on 2022-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='telegram_link',
            field=models.CharField(default='', max_length=250, verbose_name='Ссылка на товар в телеграме'),
        ),
    ]
