# Generated by Django 4.0.6 on 2022-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_telegram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на товар в телеграме'),
        ),
    ]
