# Generated by Django 4.0.6 on 2022-09-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_telegram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='price_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Цена со скидкой'),
        ),
    ]
