# Generated by Django 4.0.6 on 2022-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productprice_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
