# Generated by Django 4.0.6 on 2022-07-15 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Сумма заказа')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время заказа')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, max_length=100, verbose_name='Название товара')),
                ('product_image', models.CharField(blank=True, max_length=250, verbose_name='Изображение товара')),
                ('product_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='Цена товара')),
                ('product_quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('product_total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Общая сумма за товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказа',
                'db_table': 'orders_items',
            },
        ),
    ]
