# Generated by Django 4.0.6 on 2022-07-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usercart_user_alter_usercartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.usercart', verbose_name='Корзина'),
        ),
    ]
