# Generated by Django 4.0.6 on 2022-09-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_popular'),
        ('users', '0010_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='products.product', verbose_name='Избранное продукты'),
        ),
    ]
