# Generated by Django 4.0.6 on 2022-09-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_popular'),
        ('users', '0011_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_users', to='products.product', verbose_name='Избранное продукты'),
        ),
    ]
