# Generated by Django 4.0.6 on 2022-09-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_formwholesaler_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/blog/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=200, verbose_name='тема')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания публикации')),
            ],
            options={
                'verbose_name': 'создать блог',
                'verbose_name_plural': 'создавать блоги',
                'db_table': 'наши_блоги',
            },
        ),
    ]
