# Generated by Django 4.0.6 on 2022-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ourblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourblog',
            name='text',
        ),
        migrations.AddField(
            model_name='ourblog',
            name='full_description',
            field=models.TextField(default='', verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourblog',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
