# Generated by Django 4.0.6 on 2022-09-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutus_return'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ourblog',
            table='our_blog',
        ),
    ]
