# Generated by Django 4.0.6 on 2022-09-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ourblog_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_update_time', models.DateTimeField(auto_now=True)),
                ('sum_value', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
