# Generated by Django 4.0.6 on 2022-09-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
