# Generated by Django 4.0.6 on 2022-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='token',
            field=models.TextField(),
        ),
    ]
