# Generated by Django 4.0.6 on 2022-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_settings_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
