# Generated by Django 4.0.6 on 2022-10-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_settings_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
