# Generated by Django 4.0.6 on 2022-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='admin_phone',
            field=models.CharField(max_length=9, null=True, verbose_name='Введите номер без +998'),
        ),
    ]
