# Generated by Django 4.0.6 on 2022-10-31 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formwholesaler',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
