# Generated by Django 4.0.6 on 2022-10-31 13:26

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_settings_admin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='admin_phone',
            field=models.CharField(max_length=12, null=True, validators=[apps.main.models.phone_number_validation], verbose_name='Введите номер без +'),
        ),
    ]
