# Generated by Django 4.0.6 on 2022-11-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_aboutus_image_aboutus_keyword_aboutus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourblog',
            name='seo_keyword',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
