# Generated by Django 4.0.6 on 2022-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_ourblog_seo_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourblog',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
